### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by Chihaya-Yuka** [Chihaya-Yuka/CSTL#7]

**Comment by RohitP2005** [comment]
I am willing to help, is the issue being assigned to someone else or is still available

**Comment by Keniis0712** [comment]
Finished it.

**Comment by Chihaya-Yuka** [comment]
> I am willing to help, is the issue being assigned to someone else or is still available

This issue has been completed, but thank you for your help! :)

**Comment by RohitP2005** [comment]
Yeah okay, anytime
